apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apicurio.ui.name" . }}
  labels:
    {{- include "apicurio.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  template:
    metadata:
      name: {{ include "apicurio.ui.name" . }}
      labels:
        {{- include "apicurio.labels" . | nindent 8 }}
        app.kubernetes.io/component: ui
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "apicurio.ui.name" . }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: APICURIO_UI_HUB_API_URL
              value: {{ include "apicurio.ui.apiPath" . | quote }}
            - name: APICURIO_UI_EDITING_URL
              value: {{ include "apicurio.ui.wsPath" . | quote }}
            - name: APICURIO_UI_LOGOUT_REDIRECT_URI
              value: "/"
            - name: APICURIO_KC_AUTH_URL
              value: {{ include "apicurio.api.keycloakPath" . |quote }}
            - name: APICURIO_KC_REALM
              value: {{ .Values.keycloak.realm | quote }}
            - name: APICURIO_KC_CLIENT_ID
              value: {{ .Values.ui.app.keyCloakClientId | quote }}
            - name: APICURIO_KC_SSL_REQUIRED
              value: {{ include "apicurio.keycloak.sslRequired" . | quote }}
            - name: APICURIO_KC_DISABLE_TRUST_MANAGER
              value: {{ .Values.keycloak.disableTrustManager | quote }}
            - name: APICURIO_LOGGING_LEVEL
              value: {{ .Values.ui.app.loggingLevel | quote }}
            - name: APICURIO_MIN_HEAP
              value: {{ .Values.ui.app.minHeap | quote }}
            - name: APICURIO_MAX_HEAP
              value: {{ .Values.ui.app.maxHeap | quote }}
          resources: {{- toYaml .Values.ui.resources | nindent 12 }}
  selector:
    matchLabels:
      {{- include "apicurio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ui
