apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apicurio.api.name" . }}
  labels:
    {{- include "apicurio.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: 1
  template:
    metadata:
      name: {{ include "apicurio.api.name" . }}
      labels:
        {{- include "apicurio.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "apicurio.api.name" . }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          env:
            - name: APICURIO_DB_CONNECTION_URL
              value: {{ include "apicurio.db.connectionUrl" . }}
            - name: APICURIO_DB_DRIVER_NAME
              value: {{ include "apicurio.db.driverName" . }}
            - name: APICURIO_DB_TYPE
              value: {{ include "apicurio.db.type" . }}
            - name: APICURIO_DB_USER_NAME
              {{- include "apicurio.db.username" . | nindent 14 }}
            - name: APICURIO_DB_PASSWORD
              {{- include "apicurio.db.password" . | nindent 14 }}
            - name: APICURIO_DB_INITIALIZE
              value: "true"
            - name: APICURIO_KC_AUTH_URL
              value: {{ .Values.keycloak.url | quote }}
            - name: APICURIO_KC_REALM
              value: {{ .Values.keycloak.realm | quote }}
            - name: APICURIO_KC_CLIENT_ID
              value: {{ .Values.api.app.keyCloakClientId | quote }}
            - name: APICURIO_KC_SSL_REQUIRED
              value: {{ include "apicurio.keycloak.sslRequired" . | quote }}
            - name: APICURIO_KC_DISABLE_TRUST_MANAGER
              value: {{ .Values.keycloak.disableTrustManager | quote }}
            - name: APICURIO_LOGGING_LEVEL
              value: {{ .Values.api.app.loggingLevel | quote }}
            - name: APICURIO_MIN_HEAP
              value: {{ .Values.api.app.minHeap | quote }}
            - name: APICURIO_MAX_HEAP
              value: {{ .Values.api.app.maxHeap | quote }}
            - name: APICURIO_GITHUB_API_URL
              value: {{ .Values.api.app.githubApiUrl | quote }}
            - name: APICURIO_GITLAB_API_URL
              value: {{ .Values.api.app.gitlabApiUrl | quote }}
            - name: APICURIO_BITBUCKET_API_URL
              value: {{ .Values.api.app.bitbucketApiUrl | quote }}
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
  selector:
    matchLabels:
      {{- include "apicurio.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
