{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
  {{- include "apicurio.labels" . | nindent 4 }}
  name: {{ include "apicurio.postgresql.name" . }}
data:
  username: {{ .Values.postgresql.properties.username | b64enc }}
  password: {{ .Values.postgresql.properties.password | b64enc }}
  database: {{ .Values.postgresql.properties.database | b64enc }}
{{- end }}
