apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube-ce.postgresql.name" . }}
  labels:
    {{- include "sonarqube-ce.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  selector:
    {{- include "sonarqube-ce.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
  ports:
    - port: 5432
  type: ClusterIP
