apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    app.kubernetes.io/component: postgresql
    helm.sh/chart: {{ include "sonarqube-ce.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ include "sonarqube-ce.postgresql.fullname" . }}
      labels:
        app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "sonarqube-ce.postgresql.fullname" . }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          securityContext:
            runAsUser: 70
            runAsGroup: 70
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
                  key: database
          resources: {{- toYaml .Values.postgresql.resources | nindent 12 }}
{{- if .Values.postgresql.persistence.enabled }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ include "sonarqube-ce.postgresql.fullname" . }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
