apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    helm.sh/chart: {{ include "sonarqube-ce.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
data:
  username: {{ .Values.postgresql.username | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
  database: {{ .Values.postgresql.database | b64enc }}
