apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 5432
  type: ClusterIP
