apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "sonarqube-ce.labels" . | nindent 4 }}
  name: {{ include "sonarqube-ce.postgresql.name" . }}
data:
  username: {{ .Values.postgresql.username | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}
  database: {{ .Values.postgresql.database | b64enc }}
