{{- if .Values.postgresql.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sonarqube-ce.postgresql.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    helm.sh/chart: {{ include "sonarqube-ce.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
  storageClassName: {{ .Values.postgresql.persistence.storageClassName }}
{{- end }}
