apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube-ce.postgresql.name" . }}
  labels:
    {{- include "sonarqube-ce.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  replicas: 1
  template:
    metadata:
      name: {{ include "sonarqube-ce.postgresql.name" . }}
      labels:
        {{- include "sonarqube-ce.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgresql
    spec:
      restartPolicy: Always
      containers:
        - name: {{ include "sonarqube-ce.postgresql.name" . }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          securityContext:
            runAsUser: 70
            runAsGroup: 70
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.name" . }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.name" . }}
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.name" . }}
                  key: database
          resources: {{- toYaml .Values.postgresql.resources | nindent 12 }}
{{- if .Values.postgresql.persistence.enabled }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: {{ include "sonarqube-ce.postgresql.name" . }}
{{- end }}
  selector:
    matchLabels:
      {{- include "sonarqube-ce.labels" . | nindent 6 }}
      app.kubernetes.io/component: postgresql
