apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sonarqube-ce.sonarqube.name" . }}
  labels:
    {{- include "sonarqube-ce.labels" . | nindent 4 }}
    app.kubernetes.io/component: sonarqube
spec:
  replicas: 1
  template:
    metadata:
      name: {{ include "sonarqube-ce.sonarqube.name" . }}
      labels:
        {{- include "sonarqube-ce.labels" . | nindent 8 }}
        app.kubernetes.io/component: sonarqube
    spec:
      initContainers:
        - name: configure-sysctl
          image: bash:5.0.16
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
          command:
            - /usr/local/bin/bash
            - -c
            - |
              MAX_MAP_COUNT=$(sysctl -n vm.max_map_count)
              if [[ $MAX_MAP_COUNT -lt 262144 ]]; then
                echo "Update vm.max_map_count to 262144"
                sysctl -w vm.max_map_count=262144
              else
                echo "vm.max_map_count current value is $MAX_MAP_COUNT"
              fi

              FILE_MAX=$(sysctl -n fs.file-max)
              if [[ $FILE_MAX -lt 65536 ]]; then
                echo "Update fs.file-max to 65536"
                sysctl -w fs.file-max=65536
              else
                echo "fs.file-max current value is $FILE_MAX"
              fi
      containers:
        - name: {{ include "sonarqube-ce.sonarqube.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: SONAR_JDBC_URL
              value: "jdbc:postgresql://{{ include "sonarqube-ce.postgresql.name" . }}/{{ .Values.postgresql.database }}"
            - name: SONAR_JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.name" . }}
                  key: username
            - name: SONAR_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sonarqube-ce.postgresql.name" . }}
                  key: password
            - name: SONAR_TELEMETRY_ENABLE
              value: {{ .Values.app.enableTelemetry | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - mountPath: /opt/sonarqube/conf
              name: sonarqube-conf
            - mountPath: /opt/sonarqube/data
              name: sonarqube-data
            - mountPath: /opt/sonarqube/logs
              name: sonarqube-logs
            - mountPath: /opt/sonarqube/extensions
              name: sonarqube-extensions
            - mountPath: /opt/sonarqube/temp
              name: sonarqube-temp
      restartPolicy: Always
      volumes:
        - name: tmp
          emptyDir: {}
        - name: sonarqube-conf
          configMap:
            name: {{ include "sonarqube-ce.sonarqube.name" . }}-config
            items:
              - key: sonar.properties
                path: sonar.properties
        - name: sonarqube-data
          {{- if .Values.persistence.data.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (printf "%s-data" (include "sonarqube-ce.sonarqube.name" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: sonarqube-logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (printf "%s-logs" (include "sonarqube-ce.sonarqube.name" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: sonarqube-extensions
          {{- if .Values.persistence.extensions.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.data.existingClaim | default (printf "%s-extensions" (include "sonarqube-ce.sonarqube.name" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: sonarqube-temp
          emptyDir: {}
  selector:
    matchLabels:
      {{- include "sonarqube-ce.labels" . | nindent 6 }}
      app.kubernetes.io/component: sonarqube
