apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube-ce.sonarqube.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    app.kubernetes.io/component: sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "sonarqube-ce.name" . }}
    app.kubernetes.io/component: sonarqube
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 80
      targetPort: 9000
  type: ClusterIP
