apiVersion: v1
name: sonarqube-ce
version: 0.1.0
appVersion: "8.2-community"
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
description: A Helm chart for Kubernetes
home: https://www.sonarqube.org/
