nameOverride:
fullnameOverride:

api:
  image:
    repository: apicurio/apicurio-studio-api
    tag: 0.2.47.Final
    pullPolicy: IfNotPresent
  app:
    keyCloakClientId: apicurio-api
    loggingLevel: INFO
    minHeap: 768m
    maxHeap: 2048m
    githubApiUrl: https://api.github.com
    gitlabApiUrl: https://gitlab.com
    bitbucketApiUrl: https://api.bitbucket.org/2.0
  env: []
  resources: {}

ui:
  image:
    repository: apicurio/apicurio-studio-ui
    tag: 0.2.47.Final
    pullPolicy: IfNotPresent
  app:
    keyCloakClientId: apicurio-studio
    loggingLevel: INFO
    minHeap: 768m
    maxHeap: 2048m
    apiAbsolutePath: ""
    wsAbsolutePath: ""
  env: []
  resources: {}

ws:
  image:
    repository: apicurio/apicurio-studio-ws
    tag: 0.2.47.Final
    pullPolicy: IfNotPresent
  app:
    loggingLevel: INFO
    minHeap: 768m
    maxHeap: 2048m
  env: []
  resources: {}

dbConnection:
  driver: "mysql"
  name: apicurio
  host: localhost
  port: 3306
  username: apicurio
  password: apicurio
  # Work as environments valueFrom: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
  # You have to set secrets name and key, for example:
  # passwordFromSecretKeyRef:
  #   name: apicurio-db-secret
  #   key: password
  # Note: This value has power over password (check _helpers.tpl).
  passwordFromSecretKeyRef: {}
  properties:
    - useLegacyDatetimeCode=false

keycloak:
  url: https://studio-auth.apicur.io/auth/
  realm: apicurio
  # Set to true to disable the HTTP client trust manager when accessing Keycloak (used when making HTTPS client calls to Keycloak).
  disableTrustManager: true
  # Set APICURIO_KC_SSL_REQUIRED to ALL, else it will defined by ingress.tls.enabled parameter
  forceSSL: false
  # If you apply a service name, then it will be released in the Ingress with the keycloak.url as a path
  service:
    name: ""
    port: 8080

ingress:
  enabled: false
  annotations: {}
  host: ""
  tls:
    enabled: false
    secretName: ""
